language: generic
sudo: required
services:
- docker
git:
  clone: true
before_install:
- ssh-keyscan $TEST_IP >> $HOME/.ssh/known_hosts
install:
<<<<<<< HEAD
- cd $TRAVIS_PULL_REQUEST_SLUG
- sudo openssl aes-256-cbc -K $encrypted_key_01 -iv $encrypted_iv_01 -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- bash ./autocheck.sh queue $TEST_IP
script:
- whoami
- ssh -i ~/.ssh/skey cland@$TEST_IP "cd /opt/cloudland/ && whoami &&  bash ./autocheck.sh pull_request $TRAVIS_PULL_REQUEST_BRANCH $TRAVIS_PULL_REQUEST_SLUG"
- bash ./autocheck.sh test $TEST_IP
